In [14]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score
df = pd.read_csv("dataset_.csv")

df.head()

   age     sex     bmi  children smoker     region  medical charges
0   19  female  27.900         0    yes  southwest      16884.92400
1   18    male  33.770         1     no  southeast       1725.55230
2   28    male  33.000         3     no  southeast       4449.46200
3   33    male  22.705         0     no  northwest      21984.47061
4   32    male  28.880         0     no  northwest       3866.85520

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              1338 non-null   int64
 1   sex              1338 non-null   object
 2   bmi              1338 non-null   float64
 3   children         1338 non-null   int64
 4   smoker           1338 non-null   object
 5   region           1338 non-null   object
 6   medical charges  1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [16]:
df.isnull().sum()

age                0
sex                0
bmi                0
children           0
smoker             0
region             0
medical charges    0
dtype: int64

In [17]:

le = LabelEncoder()

df['sex'] = le.fit_transform(df['sex'])
df['smoker'] = le.fit_transform(df['smoker'])
df['region'] = le.fit_transform(df['region'])

In [18]:
df.head()

   age  sex     bmi  children  smoker  region  medical charges
0   19    0  27.900         0       1       3      16884.92400
1   18    1  33.770         1       0       2       1725.55230
2   28    1  33.000         3       0       2       4449.46200
3   33    1  22.705         0       0       1      21984.47061
4   32    1  28.880         0       0       1       3866.85520

In [19]:
df.duplicated().sum()

np.int64(1)

In [20]:
df.drop_duplicates(ignore_index =True,inplace=True)

In [21]:
X = df.drop('medical charges', axis=1)
y = df['medical charges']

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [23]:
from sklearn.tree import DecisionTreeRegressor

dtr = DecisionTreeRegressor(
    max_depth=5,
    random_state=42
)

dtr.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=5, random_state=42)

In [24]:
y_pred = dtr.predict(X_test)
from sklearn.metrics import r2_score

print( r2_score(y_test, y_pred))

0.892367145793449

In [26]:
from sklearn.metrics import mean_absolute_error

print( mean_absolute_error(y_test, y_pred))

2593.359839584189

In [27]:
from sklearn.metrics import mean_squared_error

print( mean_squared_error(y_test, y_pred))

19778189.6505053

In [29]:
from sklearn.metrics import root_mean_squared_error

print( root_mean_squared_error(y_test, y_pred))

4447.2676612168625